version: '3'

services:

    ts-compiler:
        image:                   harmish/typescript
        volumes:
            -                    ./src/frontend/ts:/workspace 
            -                    ./src/frontend/js:/output 
        command:                 "tsc --project /workspace --outDir /output --watch --pretty true"

    mysql-server:
        image:                   mysql:5.7
        hostname:                mysql-server
        environment:
            MYSQL_ROOT_PASSWORD: userpass
        volumes:
            -                    ./db/dumps:/docker-entrypoint-initdb.d
            -                    ./db/data:/var/lib/mysql
        networks:
            -                    app-smart-home

    mysql-admin:
        image:                   phpmyadmin/phpmyadmin
        environment: 
            PMA_HOST:            mysql-server
            PMA_PORT:            3306
            MYSQL_ROOT_PASSWORD: userpass
        networks:
            -                    app-smart-home
        depends_on:
            -                    mysql-server
        ports:
            -                    "8001:80"

    node-backend:
        image:                   abassi/nodejs-server:10.0-dev
        volumes:
            -                    ./src/backend:/home/node/app/src
            -                    ./src/frontend:/home/node/app/static
        networks:
            -                    app-smart-home
        depends_on:
            -                    mysql-server
        ports: 
            -                    "8000:3000"
        command:                 nodemon /home/node/app/src/index.js

networks:
    app-smart-home:
        driver:                  bridge